#! /bin/bash

printf "Making a little cleaning in your diretory (removing files ending with '~')...";
rm -f *~;
printf "Done.";

bool="TRUE";

for FILE in $@;
do
	printf "\nOpening file : \"$FILE\"...\n";
	printf "Removing trailing whitespaces...";
	(sed -e 's/[ \t]*$//' $FILE) > tmp;
	cat tmp > $FILE;
	rm tmp
	printf "Done.\n";

	i=1;

	while read line;
	do
		len=${#line};
		if [ ${len} -gt 80 ];
		then
			bool="FALSE";
			printf "WARNING : Line %i too long in file %s : %i char found\n" ${i} ${1} ${len};
			printf "Line was :\n ${line} \n \n";
		fi
		i=$(($i+1));
	done < $FILE
done

if [ $bool = "TRUE" ]
then
	printf "All documents were checked successfully.\n"
else
	printf "WARNING : You have some too long lines in your files, please change that.\n"
fi
